<a href="https://colab.research.google.com/github/JazminRivas/C-lculo-num-rico-1er-cuatri-2024/blob/main/gu%C3%ADa_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from typing import Optional, Tuple
import time

Ejercicio 1.

Escribir un programa que implemente el metodo de Jacobi y otro que implemente el metodo de Gauss-Seidel para la resoluci\'on de un sistema lineal $Ax = b$, con las siguientes condiciones:

a) que finalice si el metodo se estaciona,

b)que finalice con una advertencia si se excede cierto tope de iteraciones,

In [ ]:
#Empiezo con el punto B
def jacobi(A: np.ndarray, b: np.ndarray, x0: Optional[np.ndarray] = None, max_iter: int = 100) -> np.ndarray:
    D = np.diag(np.diag(A))
    L = np.tril(A,-1)
    U = np.triu(A,1)
    D_inv =np.linalg.inv(D)
    M = -D_inv@(L+U)
    c = D_inv@b

    if x0 is None:
        x0 = c

    # Guardo lugar para la sucesion
    # La fila i va a ser la aproximación en la iteración i
    # Las columnas van a ser las coordenadas de cada aproximación
    x = np.empty((max_iter, x0.size))

    for i in range(max_iter-1):
        x[i+1,:] = M @ x[i,:] + c

    return x

def gauss_seidel(A: np.ndarray, b: np.ndarray, x0: Optional[np.ndarray] = None, max_iter: int = 100) -> np.ndarray:
    D = np.diag(np.diag(A))
    L = np.tril(A,-1)
    U = np.triu(A,1)
    DL_inv = np.linalg.inv(D+L)

    M = -DL_inv@U
    c = DL_inv@b

    if x0 is None:
        x0 = c

    # Guardo lugar para la sucesion
    # La fila i va a ser la aproximación en la iteración i
    # Las columnas van a ser las coordenadas de cada aproximación
    x = np.empty((max_iter, x0.size))

    for i in range(max_iter-1):
        x[i+1,:] = M @ x[i,:] + c

    return x

In [ ]:
#Punto A
def jacobi_estacionado(A: np.ndarray, b: np.ndarray, x0: Optional[np.ndarray] = None, max_iter = 100, tol = 1e-8) -> np.ndarray: #lo calcula hasta que se estacione o se pase de las iteraciones
    D = np.diag(np.diag(A))
    L = np.tril(A,-1)
    U = np.triu(A,1)
    D_inv =np.linalg.inv(D)
    M = -D_inv@(L+U)
    c = D_inv@b
    iteracion = 0
    if x0 is None:
        x0 = c

    # Guardo lugar para la sucesion
    # La fila i va a ser la aproximación en la iteración i
    # Las columnas van a ser las coordenadas de cada aproximación
    x = np.empty((max_iter,x0.size))

    while iteracion < max_iter:
      x[iteracion+1,:] = M @ x[iteracion,:] + c
      if np.linalg.norm(x[iteracion + 1,:] - x[iteracion,:],2) >= tol:
        iteracion +=1
      else:
        break


    return x[:iteracion,:],iteracion + 1 #devuelve todo hasta que se estacione y la cantidad de iteraciones

#pruebo con un ejemplo
A = np.array([[-3,1],[2,6]])
b = np.array([4,4])

x,iter = jacobi_estacionado(A,b) # Ponerle otro x0 para ver que pasa despues de que ande
print("la solucion es", A@x[-1,:], "y las iteraciones son",iter) #espectacular :D

def GS_estacionado(A: np.ndarray, b: np.ndarray, x0: Optional[np.ndarray] = None, max_iter: int = 100, tol = 1e-8) -> np.ndarray:
 D = np.diag(np.diag(A))
 L = np.tril(A,-1)
 U = np.triu(A,1)
 DL_inv = np.linalg.inv(D+L)
 M = -DL_inv@U
 c = DL_inv@b
 iteracion = 0
 if x0 is None:
  x0 = c

    # Guardo lugar para la sucesion
    # La fila i va a ser la aproximación en la iteración i
    # Las columnas van a ser las coordenadas de cada aproximación
  x = np.empty((max_iter, x0.size))

  while iteracion < max_iter:
      x[iteracion+1,:] = M @ x[iteracion,:] + c
      if np.linalg.norm(x[iteracion + 1,:] - x[iteracion,:],2) >= tol:
        iteracion +=1
      else:
          break


  return x[:iteracion,:],iteracion + 1 #devuelve todo hasta que se estacione y la cantidad de iteraciones
Aa = np.array([[1,1/2,1/2],
              [1/2,1,1/2],
              [1/2,1/2,1]])
bb = np.array([2,2,2])

xgs, itergs = GS_estacionado(Aa,bb)
print("ajsjdhd", Aa@xgs[-1,:],"las iter son", itergs) #funciona perfecto

la solucion es [4.00000002 3.99999994] y las iteraciones son 19
ajsjdhd [1.99999999 2.00000001 2.        ] las iter son 20


Hacer un codigo que calcule la descomposicion LU de una matriz.

In [ ]:
def tiene_lu(A,eps): #eps es el epsilon de maquina
    #Dada una matriz A, devuelve True si tiene descomposición LU, o False en caso contrario


    res = True

    for i in range(np.shape(A)[0]):
      if np.abs(np.linalg.det(A[:i, :i])) < eps: #si el determinante esta muy cerca de 0, no s inversible
        res = False
    return res
    pass

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    if tiene_lu:

      for i in range(n):
        # Matriz L tiene unos en su diagonal
          L[i, i] = 1

        # Calcula la parte superior de la matriz U
          for j in range(i, n):
              U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        # Calcula la parte inferior de la matriz L
          for j in range(i + 1, n):
              L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

      return L, U
    else:
      print("No tiene factorizacion LU")

# Ejemplo de uso
A = np.array([[2, -1, 1], [1, 3, 2], [1, 1, 4]])
L, U = lu_decomposition(A)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U)
print(L@U)

Matriz L:
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.42857143 1.        ]]
Matriz U:
[[ 2.         -1.          1.        ]
 [ 0.          3.5         1.5       ]
 [ 0.          0.          2.85714286]]
[[ 2. -1.  1.]
 [ 1.  3.  2.]
 [ 1.  1.  4.]]


Cholesky

In [ ]:
def es_simetrica(A):
  for i in range(len(A)):
        for j in range(i, len(A)):  # Podemos empezar desde i para evitar comparar dos veces
            if A[i][j] != A[j][i]:
                return False


  return True

def es_definida_positiva(A):
    # Verificar si todos los autovalores son positivos
    autovalores = np.linalg.eigvals(A)
    return np.all(autovalores > 0) #devuelve true si todos los autovalores son mayores a 0

def cholesky(A):
  if es_simetrica(A) and es_definida_positiva(A):
    L,U = lu_decomposition(A)
    return L, L.T
  else:
    print(A, "no tiene descomposición de cholesky")

matriz1 = np.array([[4, 2, 2],[2, 2, 1],[2, 1, 3]])
matriz2 = np.array([[0, 2, 3],[2, 5, 6],[3, 1, 2]])
print(cholesky(matriz1))
print(cholesky(matriz2))

(array([[1. , 0. , 0. ],
       [0.5, 1. , 0. ],
       [0.5, 0. , 1. ]]), array([[1. , 0.5, 0.5],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ]]))
[[0 2 3]
 [2 5 6]
 [3 1 2]] no tiene descomposición de cholesky
None


Método SOR

In [ ]:
def metodo_sor(A: np.ndarray, b: np.ndarray, tolerancia,w, x0: Optional[np.ndarray] = None, max_iter = 1000) -> np.ndarray:
  D = np.diag(np.diag(A))
  L = np.tril(A,-1)
  U = np.triu(A,1)
  D_inv = np.linalg.inv(D+(w*L))
  Bsor = D_inv @ ((1-w)*D - w*U)
  Csor = D_inv @ (w*b)
  if x0 is None:
      x0 = np.zeros(len(b))
  x = x0.copy()
  for i in range(max_iter):
        x_nuevo = Bsor @ x + Csor
        if np.linalg.norm(x_nuevo - x, 2) < tolerancia:
            return x_nuevo, i+1   #como arranca desde el 0, le sumo 1 y es la iteracion que hizo que converja
        x = x_nuevo

  return x, max_iter

#pruebo con un ejemplo
A = np.array([[4,3,0],[3,4,-1],[0,-1,4]])
b = np.array([24,30,-24])
sol = np.linalg.solve(A,b)
print(sol)
w = 0.9
x0 = np.array([1,1,1])
tolerancia = 1e-8
x,cantI = metodo_sor(A,b,tolerancia,w,x0,100)
print(x,cantI)
#funciona bien :D


[ 3.  4. -5.]
[ 3.00000001  3.99999999 -5.        ] 45
